services:
  nsv-es:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.16
    container_name: nsv-es
    environment:
      - cluster.name=nsv-cluster
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - nsv-es-data:/usr/share/elasticsearch/data

  nsv-initial-data-uploader:
    image: rppedraza/nsv-initial-data-uploader
    container_name: nsv-initial-data-uploader
    build:
      context: ./initial-data-uploader
      additional_contexts:
        root: ..
      dockerfile: Dockerfile.python
    links:
      - nsv-es
    depends_on:
      - nsv-es

  nsv-backend:
    image: rppedraza/nsv-backend
    container_name: nsv-backend
    build:
      context: ./backend
      additional_contexts:
        root: ..
    links:
      - nsv-es
    depends_on:
      - nsv-es

  nsv-frontend:
    image: rppedraza/nsv-frontend
    container_name: nsv-frontend
    build:
      context: ./frontend
      additional_contexts:
        root: ..
    links:
      - nsv-backend
    depends_on:
      - nsv-backend
    environment:
      # This is where the server name should be changed.
      # There's no need to create a custom image on every deployment.
      - NSV_FRONTEND_SERVERNAME=localhost
      # This will make some messages show at startup.
      - NSV_FRONTEND_DEBUG=true
    ports:
      - "80:80"

volumes:
  nsv-es-data:
